# Generated by Django 3.1.4 on 2020-12-27 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coffee',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
